### ISSUE TITLE
Entry Manager showing old version after edit

### ISSUE THREAD

**Issue by retep998** [FTB-Gamepedia/OreDict#69] opened 2019-01-07 04:27 UTC
When changing the name of an entry using the Entry Manager, after saving the results the old name is shown. Upon refreshing the page however the new name is shown. This leads me to believe that the name to display is fetched *before* the edit is actually written to the database.

**Comment by elifoster** [comment] 2019-01-18 00:37
Duplicate of #68

**Closed by elifoster** 2019-01-18 00:37 UTC
Labels: bug, special
